// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/clusters": {
    params: {};
  };
  "/simular-leads": {
    params: {};
  };
  "/dashboard/clientes": {
    params: {};
  };
  "/dashboard/nps": {
    params: {};
  };
  "/dashboard/contratos": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/clusters" | "/simular-leads" | "/dashboard/clientes" | "/dashboard/nps" | "/dashboard/contratos";
  };
  "components/Layout.tsx": {
    id: "components/Layout";
    page: "/" | "/clusters" | "/simular-leads" | "/dashboard/clientes" | "/dashboard/nps" | "/dashboard/contratos";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/clusters.tsx": {
    id: "routes/clusters";
    page: "/clusters";
  };
  "routes/simular-leads.tsx": {
    id: "routes/simular-leads";
    page: "/simular-leads";
  };
  "routes/dashboard.clientes.tsx": {
    id: "routes/dashboard.clientes";
    page: "/dashboard/clientes";
  };
  "routes/dashboard.nps.tsx": {
    id: "routes/dashboard.nps";
    page: "/dashboard/nps";
  };
  "routes/dashboard.contratos.tsx": {
    id: "routes/dashboard.contratos";
    page: "/dashboard/contratos";
  };
};